import React from 'react'

function Section2() {
  return (
    <div>
      <h1>Section 2</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae alias, asperiores tempore, omnis necessitatibus ullam totam perferendis veniam perspiciatis repellendus ab praesentium blanditiis earum, neque facilis? Facilis ea fugit enim voluptas voluptatem quam eius amet dolor sunt! Recusandae officiis reiciendis voluptas ducimus delectus laudantium officia corrupti! Odio eligendi voluptatem officia dolorum, dolores quibusdam ratione dicta perferendis sint itaque natus consequatur numquam tenetur et tempora laboriosam dignissimos praesentium deserunt delectus, quae, exercitationem commodi facilis. Culpa quasi inventore maxime, alias adipisci beatae, distinctio consequuntur est dolore blanditiis ipsam vitae quam assumenda mollitia, provident consectetur. Eius vel eveniet voluptas nulla sapiente repellat quo?</p>
      <hr />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat vero eum in quo consequatur quia reiciendis dolores temporibus cumque, magni tempora amet dolor fugiat dignissimos adipisci quisquam debitis facilis laudantium provident officia rem dolorem. Iste id reiciendis culpa esse sapiente! Molestias ut sapiente voluptate accusamus cum sed hic quibusdam alias consequatur aliquid commodi repellendus dolorum quasi reiciendis deleniti explicabo, similique dolor laborum facilis perspiciatis soluta in ratione doloribus libero! Reprehenderit eius nobis nemo, sint nam velit at asperiores cum temporibus fugit ducimus numquam. Atque illo nemo iusto consectetur repellat accusamus qui ad quibusdam, cum quidem beatae facilis quae et reiciendis sit magni eum omnis eius, laborum nulla. Assumenda, illum non. Rerum minus enim facere inventore atque doloribus nesciunt id! Veniam consectetur, nesciunt dolorem tenetur explicabo eum possimus voluptatibus quasi expedita, officiis error ipsa enim minus doloremque blanditiis quam accusantium amet consequatur fugiat similique maiores ducimus delectus quis tempore. Maiores earum iste perspiciatis eius. Facilis omnis et quas in quis? Quaerat voluptates eius libero debitis numquam, totam maxime! Itaque, totam, possimus incidunt voluptatem consectetur non quam tempore in laudantium vitae accusantium asperiores. Ad eum officia veniam molestias, dignissimos magnam praesentium quam? Consequuntur laborum enim hic delectus. Reprehenderit soluta, doloremque recusandae iste nobis, illo consectetur maxime sapiente beatae aperiam dicta iusto, fuga rem aut atque a natus. Quae enim voluptates corrupti consequatur obcaecati cum atque, saepe quo eos amet qui natus ex id ratione, beatae aliquam dolorem? Magni doloremque suscipit molestiae dolor minus est dolore accusantium pariatur, culpa impedit itaque sequi ducimus placeat ut ratione sint ad consectetur exercitationem nisi quidem tempore repellendus. Id quasi recusandae vero voluptate ad temporibus libero veniam autem a veritatis consequatur reprehenderit aspernatur, fuga similique laborum pariatur qui suscipit doloribus, facilis ex, aperiam vitae. Doloremque aspernatur consequatur quibusdam, cumque doloribus error nisi voluptate quam? Maxime, asperiores enim!</p>
    </div>
  )
}

export default Section2