import React from 'react'

function Section1() {
  return (
    <div>
      <h1>Section 1</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae cum facilis maxime recusandae ratione nobis eaque cumque quisquam amet nesciunt fugiat qui alias molestias quidem iure, beatae omnis vero dolores voluptatum quam illum voluptatibus nihil neque. Dignissimos omnis adipisci perferendis soluta, quibusdam nostrum dolorum libero ut quo nihil facere laudantium quam quas ipsa similique aut debitis exercitationem dolore quia cumque maxime! Similique quas aliquid non tenetur, dolore quam, illum qui deleniti voluptatum sunt cupiditate? Sint libero cumque numquam a quos perspiciatis magnam voluptatum obcaecati ex facere illum eius, quam ratione reiciendis aliquid error iusto minima explicabo perferendis? Quae similique illo quidem incidunt, minus ex, vitae corrupti omnis id a cupiditate veniam ipsa repellendus autem nesciunt soluta quaerat rerum eius? Excepturi corporis nobis quae ducimus molestiae harum, officia reiciendis rem aliquid nam nemo, voluptates possimus numquam. Vel eos molestias culpa distinctio vitae error odit fuga modi ullam temporibus iure ratione inventore maxime impedit natus ea tempora nam, similique voluptas nesciunt eligendi placeat. Praesentium, repudiandae. Nulla commodi dolore, blanditiis nostrum saepe, repellat officia consectetur numquam temporibus minus quam! Laboriosam, delectus? Necessitatibus consequuntur minus quasi quam ipsam beatae tempora, velit eaque voluptatibus eos nam totam voluptates sunt odit praesentium sequi cumque numquam! Alias laborum nam consectetur accusantium, assumenda totam quos, itaque aliquam similique esse voluptates omnis, beatae provident eligendi! Quo numquam animi, laboriosam neque deserunt magnam culpa eveniet harum doloremque nobis minima ducimus debitis expedita sunt cum, et suscipit corporis voluptates veniam. Quidem cumque ipsam, atque reiciendis veniam inventore sit? Dicta enim tempore temporibus sed, atque consequuntur eius odit exercitationem! Reiciendis, perspiciatis molestiae, optio vitae sint distinctio quam alias asperiores reprehenderit sapiente quas voluptate rem impedit consequuntur quidem quasi, non possimus dolor sit animi porro tempora nemo culpa iste. Labore modi quia exercitationem ut, nam asperiores earum maxime dolores iste inventore ad? Ipsam sapiente laboriosam minus placeat a obcaecati beatae reiciendis, vero commodi expedita est accusantium dolor vel sed, repellat aliquam delectus! Maxime beatae sapiente quasi temporibus officia, neque molestiae consequuntur laboriosam amet tempore soluta facilis a eos, id aspernatur! Vero perferendis, a corrupti dolore magnam praesentium necessitatibus rerum eos nulla, amet reiciendis!</p>
      <hr />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt doloremque dolorum nihil, atque necessitatibus libero, suscipit error corrupti accusantium magnam veritatis modi voluptate eaque. Voluptatum nobis laborum ducimus aliquid nostrum ratione eligendi delectus quidem vitae expedita excepturi, nihil et modi a sapiente pariatur officiis doloribus sed! Corporis illo asperiores tempora magni amet expedita dolores alias architecto, corrupti sed, repudiandae eius unde saepe accusantium magnam, excepturi omnis aliquam qui quibusdam optio. Molestiae minima laudantium soluta culpa dolorum. Quasi molestias minima enim cumque qui obcaecati, perferendis possimus fugiat ea soluta rerum, quam, facere fuga? Voluptatibus accusantium quos, quia mollitia magni minus consequatur inventore dolor pariatur veniam nesciunt ratione odio. Aliquid voluptate, sunt, incidunt vel recusandae laborum, quae cumque sed adipisci a dicta eveniet molestias maxime atque rerum rem beatae aut enim! Minus ex nam expedita ipsam placeat, rerum libero nulla odio fugit nihil atque incidunt, quisquam dignissimos! Dicta, tempore quaerat beatae minus officia vel deserunt vitae facilis. Delectus eos ratione incidunt omnis quibusdam sequi ipsam! Dolorum doloremque sunt, soluta laudantium quidem rem nemo debitis maiores suscipit inventore modi architecto reiciendis commodi est dolorem laborum molestias, earum at velit id voluptas. Quod, illum voluptatum quisquam illo similique corrupti voluptatem harum. Error, itaque earum!</p>
    </div>
  )
}

export default Section1